### ISSUE TITLE
Lamport's logic clock implementation in server

### ISSUE THREAD

**Issue by kristianwang** [justincurewitz/ee360p#2]
Look up page 135 and implement the algorithm.

**Comment by justincurewitz** [comment]
Starting this now

**Comment by kristianwang** [comment]
Lamport's algorithm:
1 To request the critical section, a process sends a timestamped message to all other processes and adds a timestamped request to the queue.
2 On receiving a request message, the request and its timestamp are stored in the queue and a timestamped acknowledgment is sent back.
3 To release the critical section, a process sends a release message to all other processes.
4 On receiving a release message, the corresponding request is deleted from the queue.
5 A process determines that it can access the critical section if and only if (1) it has a request in the queue with timestamp t,(2) t is less than all other requests in the queue, and (3) it has received a message from every other process with timestamp greater than t (the request acknowledgments ensure this).
